name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  print-input:
    runs-on: ubuntu-latest
    steps:
      - name: Show selected environment
        run: echo "You selected environment${{ github.event.inputs.environment }}"